/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import eje5.Eje5;
import java.awt.Color;
import java.util.regex.*;

import static javax.swing.JOptionPane.*;

/**
 *
 * @author ketro
 */
public class VentanaInscripcion extends javax.swing.JDialog {

    private boolean existe;
    
    public VentanaInscripcion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        bAceptar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcNombreE = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfHora = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfDni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNombreP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfPApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfSApellido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jlError = new javax.swing.JLabel();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Inscripción en un evento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento"));

        jLabel2.setText("Nombre");

        jcNombreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcNombreEActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha");

        tfFecha.setEnabled(false);

        jLabel4.setText("Hora");

        tfHora.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Persona"));

        jLabel5.setText("Dni:");

        tfDni.setEditable(false);
        tfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDniActionPerformed(evt);
            }
        });

        jLabel6.setText("Nombre:");

        tfNombreP.setEnabled(false);
        tfNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombrePActionPerformed(evt);
            }
        });

        jLabel7.setText("Primer apellido:");

        tfPApellido.setEnabled(false);
        tfPApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPApellidoActionPerformed(evt);
            }
        });

        jLabel8.setText("Segundo apellido:");

        tfSApellido.setEnabled(false);
        tfSApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSApellidoActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefono:");

        tfTelefono.setEnabled(false);
        tfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoActionPerformed(evt);
            }
        });

        jlError.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jlError.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tfPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jlError)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlError))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfSApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(bCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(bCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        Eje5.salirv(this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void jcNombreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcNombreEActionPerformed
        try
        {
            if (jcNombreE.getSelectedIndex() != -1)
            {
                String nombre = String.valueOf(jcNombreE.getSelectedItem());
                
                defectof(false,true);
                tfFecha.setText(Eje5.mostrardato("Fecha",nombre));
                tfHora.setText(Eje5.mostrardato("Hora",nombre));
                tfDni.requestFocus();
            }
            else
            {
                defectof(true,false);
                jcNombreE.requestFocus();
                tfFecha.setText("");
                tfHora.setText("");
            }
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jcNombreEActionPerformed

    private void tfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDniActionPerformed
       try
       {
           if(tfDni.getText().isEmpty())
               throw new Exception("CAMPO OBLIGATORIO");
           
           if(!validardato(tfDni.getText().toUpperCase(),"^[\\d]{8}[A-Z]?"))
                throw new Exception("DNI INCORRECTO");
           
           defecto(tfDni);
           
           if(Eje5.buscarpersona(tfDni.getText().toUpperCase()))
           {
               existe = true;
               tfDni.setEditable(false);
               mostrardatos();
               bAceptar.setEnabled(true);
               bAceptar.requestFocus();
           }
           else
           {
               existe = false;
               cambio(tfDni,tfNombreP);
           }
       }
       catch (Exception e)
       {
           error(e,tfDni);
       }
    }//GEN-LAST:event_tfDniActionPerformed

    public void cambio(javax.swing.JTextField ji,javax.swing.JTextField js)
    {
        ji.setEnabled(false);
        js.setEnabled(true);
        js.requestFocus();
    }
    
    public void mostrardatos()
    {
        tfNombreP.setText(Eje5.getNombre());
        tfPApellido.setText(Eje5.getPApellido());
        tfSApellido.setText(Eje5.getSApellido());
        tfTelefono.setText(Eje5.getTelefono());
    }
    
    public void error(Exception e,javax.swing.JTextField jt)
    {
        jlError.setText(e.getMessage());
        jt.setBackground(Color.red);
        jt.requestFocus();
    }
    
    public void defecto(javax.swing.JTextField jt)
    {
        jlError.setText("");
        jt.setBackground(Color.WHITE);
    }
    
    public boolean validardato(String dato,String expre)
    {
        Pattern pt = Pattern.compile(expre);
        Matcher m = pt.matcher(dato);
        
        return m.matches();
        /*
            if (!m.matches())
                return false;
            return true;
        */
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try
        {
            if (!Eje5.llenarinscri(jcNombreE)) 
            {
                showMessageDialog(this,"NO HAY EVENTOS PARA INSCRIBIRSE");
                Eje5.salirv(this);
            }
            
            jcNombreE.setSelectedIndex(-1);
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage()); 
        } 
    }//GEN-LAST:event_formWindowOpened

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        if (existe)
        {
            try
            {
                if (Eje5.buscarinscri(String.valueOf(jcNombreE.getSelectedItem()),tfDni.getText().toUpperCase()))
                    throw new Exception("ESTA PERSONA YA ESTA INSCRITA EN ESTE EVENTO");
                
                Eje5.insertarasistencia(String.valueOf(jcNombreE.getSelectedItem()),tfDni.getText().toUpperCase(),this);           
            }
            catch (Exception e)
            {
                showMessageDialog(this,e.getMessage());
                Eje5.salirv(this);
            }
        }
        else
        {
            try
            {
                Eje5.insertarpersona(tfDni.getText().toUpperCase(),tfNombreP.getText(),tfPApellido.getText(),tfSApellido.getText(),tfTelefono.getText());
                Eje5.insertarasistencia(String.valueOf(jcNombreE.getSelectedItem()), tfDni.getText(), this);
            }
            catch (Exception e)
            {
                showMessageDialog(this,e.getMessage());
            }
        }
    }//GEN-LAST:event_bAceptarActionPerformed

    private void tfNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombrePActionPerformed
        try
        {
            if (tfNombreP.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            
            if (!validardato(tfNombreP.getText().toUpperCase(),"^[A-Z]+$"))
                throw new Exception("NOMBRE INCORRECTO");
            
            defecto(tfNombreP);
            cambio(tfNombreP,tfPApellido);
        }
        catch (Exception e)
        {
            error(e,tfNombreP);
        }
    }//GEN-LAST:event_tfNombrePActionPerformed

    private void tfPApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPApellidoActionPerformed
        try
        {
            if (tfPApellido.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            
            if (!validardato(tfPApellido.getText().toUpperCase(),"^[A-Z]+$"))
                throw new Exception("PRIMER APELLIDO INCORRECTO");
            
            defecto(tfPApellido);
            cambio(tfPApellido,tfSApellido);
        }
        catch (Exception e)
        {
            error(e,tfPApellido);
        }
    }//GEN-LAST:event_tfPApellidoActionPerformed

    private void tfSApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSApellidoActionPerformed
        try
        {
            if (tfSApellido.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            
            if (!validardato(tfSApellido.getText().toUpperCase(),"^[A-Z]+$"))
                throw new Exception("SEGUNDO APELLIDO INCORRECTO");
            
            defecto(tfSApellido);
            cambio(tfSApellido,tfTelefono);
        }
        catch (Exception e)
        {
            error(e,tfSApellido);
        }
    }//GEN-LAST:event_tfSApellidoActionPerformed

    private void tfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoActionPerformed
        try
        {
            if (tfTelefono.getText().isEmpty())
                throw new Exception("CAMPO OBLIGATORIO");
            
            if (!validardato(tfTelefono.getText().toUpperCase(),"^[6|7][\\d]{8}$"))
                throw new Exception("TELEFONO INCORRECTO");
            
            defecto(tfTelefono);
            tfTelefono.setEnabled(false);
            bAceptar.setEnabled(true);
            bAceptar.requestFocus(); 
        }
        catch (Exception e)
        {
            error(e,tfTelefono);
        }
    }//GEN-LAST:event_tfTelefonoActionPerformed

    public void defectof(boolean valor,boolean v)
    {
        jcNombreE.setEnabled(valor);
        tfDni.setEditable(v);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaInscripcion dialog = new VentanaInscripcion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcNombreE;
    private javax.swing.JLabel jlError;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfFecha;
    private javax.swing.JTextField tfHora;
    private javax.swing.JTextField tfNombreP;
    private javax.swing.JTextField tfPApellido;
    private javax.swing.JTextField tfSApellido;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
