/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import eje5.Eje5;
import java.time.*;
import java.time.format.DateTimeFormatter;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author Ketro
 */
public class VentanaBorraryModificar extends javax.swing.JDialog {
    
    private static String dato;
    private static LocalDate fecha;
    private static LocalTime horai;
    private static LocalTime horaf;
    private static Integer aforo;
    
    public VentanaBorraryModificar(java.awt.Frame parent, boolean modal){
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public VentanaBorraryModificar(java.awt.Frame parent, boolean modal,String operacion){
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        bLugar.setVisible(false);
        bFechayHoras.setVisible(false);
        bAforo.setVisible(false);
        bBorrar.setVisible(false);
        bBorrarTodo.setVisible(false);
        jLugar.setVisible(false);
        jpFechayHoras.setVisible(false);
        jpAforo.setVisible(false);
        bModificar.setVisible(false);
        
        if (operacion.equals("Borrar"))
            habilitar("¿Que evento deseas eliminar?",bBorrar,bBorrarTodo);
        else
        {
            habilitar("¿Que evento deseas modificar?",bLugar,bFechayHoras);
            bAforo.setVisible(true);
            bModificar.setVisible(true);
            bModificar.setEnabled(false);
        }
    }
    
    public void habilitar(String texto,javax.swing.JButton jb, javax.swing.JButton jd)
    {
        jLabel1.setText(texto);
        jb.setVisible(true);
        jd.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcNombreEvento = new javax.swing.JComboBox<>();
        bBorrar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bBorrarTodo = new javax.swing.JButton();
        bLugar = new javax.swing.JButton();
        bFechayHoras = new javax.swing.JButton();
        bAforo = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpFechayHoras = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFechayHoras = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jfFecha = new javax.swing.JFormattedTextField();
        jfHorai = new javax.swing.JFormattedTextField();
        jfHoraf = new javax.swing.JFormattedTextField();
        jpAforo = new javax.swing.JPanel();
        jAforo = new javax.swing.JPanel();
        jfAforo = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpLugar = new javax.swing.JPanel();
        jLugar = new javax.swing.JPanel();
        jcLugar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(jcNombreEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 132, 312, -1));

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(bBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 206, 112, -1));

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 660, 128, -1));

        bBorrarTodo.setText("Borrar Todo");
        bBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(bBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 206, 131, -1));

        bLugar.setText("Lugar");
        bLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLugarActionPerformed(evt);
            }
        });
        getContentPane().add(bLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 286, 92, -1));

        bFechayHoras.setText("Fecha y Horas");
        bFechayHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFechayHorasActionPerformed(evt);
            }
        });
        getContentPane().add(bFechayHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        bAforo.setText("Aforo");
        bAforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAforoActionPerformed(evt);
            }
        });
        getContentPane().add(bAforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 286, 90, -1));

        bModificar.setText("Modificar");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });
        getContentPane().add(bModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, 119, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Formato"));

        jLabel5.setText("Fecha → dd/MM/yyyy");

        jLabel6.setText("Hora Inicio → HH:mm");

        jLabel7.setText("Hora Finalizacion → HH:mm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jFechayHoras.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha y Horas"));

        jLabel2.setText("Fecha:");

        jLabel3.setText("Hora inicio:");

        jLabel4.setText("Hora finalizacion:");

        jfFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jfFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfFechaActionPerformed(evt);
            }
        });

        jfHorai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        jfHorai.setEnabled(false);
        jfHorai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfHoraiActionPerformed(evt);
            }
        });

        jfHoraf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        jfHoraf.setEnabled(false);
        jfHoraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfHorafActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFechayHorasLayout = new javax.swing.GroupLayout(jFechayHoras);
        jFechayHoras.setLayout(jFechayHorasLayout);
        jFechayHorasLayout.setHorizontalGroup(
            jFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFechayHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFechayHorasLayout.createSequentialGroup()
                        .addComponent(jfFecha)
                        .addGap(22, 22, 22))
                    .addGroup(jFechayHorasLayout.createSequentialGroup()
                        .addComponent(jfHorai)
                        .addGap(16, 16, 16))
                    .addGroup(jFechayHorasLayout.createSequentialGroup()
                        .addComponent(jfHoraf)
                        .addGap(12, 12, 12))))
        );
        jFechayHorasLayout.setVerticalGroup(
            jFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFechayHorasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jfHorai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jfHoraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jpFechayHorasLayout = new javax.swing.GroupLayout(jpFechayHoras);
        jpFechayHoras.setLayout(jpFechayHorasLayout);
        jpFechayHorasLayout.setHorizontalGroup(
            jpFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFechayHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFechayHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpFechayHorasLayout.setVerticalGroup(
            jpFechayHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFechayHorasLayout.createSequentialGroup()
                .addComponent(jFechayHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jpFechayHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 358, -1, 268));

        jAforo.setBorder(javax.swing.BorderFactory.createTitledBorder("Aforo"));
        jAforo.setToolTipText("");

        jfAforo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jfAforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfAforoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAforoLayout = new javax.swing.GroupLayout(jAforo);
        jAforo.setLayout(jAforoLayout);
        jAforoLayout.setHorizontalGroup(
            jAforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAforoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jfAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jAforoLayout.setVerticalGroup(
            jAforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAforoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jfAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Formato"));

        jLabel8.setText("Aforo → Numero Entero");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpAforoLayout = new javax.swing.GroupLayout(jpAforo);
        jpAforo.setLayout(jpAforoLayout);
        jpAforoLayout.setHorizontalGroup(
            jpAforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAforoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAforoLayout.setVerticalGroup(
            jpAforoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAforoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jpAforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 352, -1, -1));

        jLugar.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar"));

        javax.swing.GroupLayout jLugarLayout = new javax.swing.GroupLayout(jLugar);
        jLugar.setLayout(jLugarLayout);
        jLugarLayout.setHorizontalGroup(
            jLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcLugar, 0, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLugarLayout.setVerticalGroup(
            jLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLugarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jcLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpLugarLayout = new javax.swing.GroupLayout(jpLugar);
        jpLugar.setLayout(jpLugarLayout);
        jpLugarLayout.setHorizontalGroup(
            jpLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLugarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpLugarLayout.setVerticalGroup(
            jpLugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLugarLayout.createSequentialGroup()
                .addComponent(jLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
        );

        getContentPane().add(jpLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 358, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarTodoActionPerformed
        try
        {
             Eje5.borrartodo(this);
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_bBorrarTodoActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        try 
        {
            Eje5.borrar(String.valueOf(jcNombreEvento.getSelectedItem()),this);
        } 
        catch (Exception ex) 
        {
            showMessageDialog(this,ex.getMessage());
        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        Eje5.salirv(this);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try
        {
            Eje5.mostrarnombre(jcNombreEvento);
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void bFechayHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFechayHorasActionPerformed
        desactivar("FechaHora",false,jpFechayHoras,jLugar,jpAforo,bLugar,bAforo);
        jfFecha.requestFocus();
    }//GEN-LAST:event_bFechayHorasActionPerformed

    private void bLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLugarActionPerformed
        desactivar("Lugar",true,jLugar,jpFechayHoras,jpAforo,bFechayHoras,bAforo);
        
        jcLugar.removeAllItems();
        llenarCombo();
        jcLugar.requestFocus();
    }//GEN-LAST:event_bLugarActionPerformed

    public void desactivar(String v,boolean valor,javax.swing.JPanel jp,javax.swing.JPanel jo,javax.swing.JPanel ju,javax.swing.JButton jb,javax.swing.JButton jbs)
    {
        dato = v;
        jcNombreEvento.setEnabled(false);
        bModificar.setEnabled(valor);
        jp.setVisible(true);
        jo.setVisible(false);
        ju.setVisible(false);
        jb.setEnabled(false);
        jbs.setEnabled(false);
    }
    
    private void llenarCombo()
    {
        try
        {
            Eje5.llenarlugar(jcLugar,String.valueOf(jcNombreEvento.getSelectedItem()));
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
        }
    }
    
    private void bAforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAforoActionPerformed
        desactivar("Aforo",false,jpAforo,jpFechayHoras,jLugar,bLugar,bFechayHoras);
        jfAforo.requestFocus();
    }//GEN-LAST:event_bAforoActionPerformed

    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed
        switch (dato)
        {
            case "Lugar":
                comprobarlugar();
                break;
            case "Aforo":
                modificaraforo();
                break;
            default:
                comprobarfecha();        
        }
    }//GEN-LAST:event_bModificarActionPerformed

    public void comprobarlugar()
    {
        try
        {
            if (Eje5.comprolugar(String.valueOf(jcLugar.getSelectedItem()),String.valueOf(jcNombreEvento.getSelectedItem())))
               throw new Exception("YA HAY UN EVENTO A ESAS HORAS EN EL LUGAR");
            
            Eje5.modificarlugar(String.valueOf(jcLugar.getSelectedItem()),String.valueOf(jcNombreEvento.getSelectedItem()),this);
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
            jcLugar.requestFocus();
            jcLugar.setEnabled(true);
        }
    }
    
    public void modificaraforo()
    {
        try
        {
            Eje5.modificaraforo(aforo,String.valueOf(jcNombreEvento.getSelectedItem()),this);
        }
        catch(Exception e)
        {
            showMessageDialog(this,e.getMessage());
        }
    }
    
    public void comprobarfecha()
    {
       try
       {
           horai = LocalTime.parse(jfHorai.getText());
           horaf = LocalTime.parse(jfHoraf.getText());
           
           if (horai.isAfter(horaf))
               throw new Exception("LA HORA INICIAL NO DEBE SER POSTERIOR A LA HORA FINAL");
           
           if(horai.equals(horaf))
               throw new Exception("LA HORA INICIAL NO PUEDE SER IGUAL A LA HORA FINAL");
           
           Eje5.modificarfechayhora(fecha,horai,horaf,this,String.valueOf(jcNombreEvento.getSelectedItem()));
       }
       catch (Exception e)
       {
           showMessageDialog(this,e.getMessage());
           jfHorai.setEnabled(true);
           jfHoraf.setEnabled(false);
           jfHorai.requestFocus();
           bModificar.setEnabled(false);
           jfHorai.setText("");
       }
    }
    
    private void jfFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfFechaActionPerformed
        try
        {
            fecha = LocalDate.parse(jfFecha.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        
            if (fecha.isBefore(LocalDate.now()))
                throw new Exception("LA FECHA TECLEADA NO VALIDA");
            
            if (!Eje5.comprobarfecha(fecha,String.valueOf(jcNombreEvento.getSelectedItem())))
                throw new Exception("YA HAY UN ACONTECIMIENTO ESE DIA");
            
            cambiar(jfFecha,jfHorai);
        }
        catch (Exception e)
        {
            showMessageDialog(this,e.getMessage());
            jfFecha.setText("");
        }       
    }//GEN-LAST:event_jfFechaActionPerformed

    public void cambiar(javax.swing.JFormattedTextField jf,javax.swing.JFormattedTextField jc)
    {
        jf.setEnabled(false);
        jc.setEnabled(true);
        jc.requestFocus();
    }
    
    private void jfHoraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfHoraiActionPerformed
        cambiar(jfHorai,jfHoraf);
        jfHoraf.setText("");
    }//GEN-LAST:event_jfHoraiActionPerformed

    private void jfHorafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfHorafActionPerformed
        jfHoraf.setEnabled(false);
        bModificar.setEnabled(true);
        bModificar.requestFocus();
    }//GEN-LAST:event_jfHorafActionPerformed

    private void jfAforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfAforoActionPerformed
        try
        {
              aforo = Integer.parseInt(jfAforo.getText());
             
             if (aforo <= Eje5.cantidadaforo(String.valueOf(jcNombreEvento.getSelectedItem())))
                 throw new Exception("SOLO SE PUEDE AMPLIAR EL AFORO");
             
             jfAforo.setEnabled(false);
             bModificar.setEnabled(true);
             bModificar.requestFocus();
        }
        catch(Exception e)
        {
            showMessageDialog(this,e.getMessage());
            jfAforo.setText("");
            jfAforo.requestFocus();
        }
    }//GEN-LAST:event_jfAforoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBorraryModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBorraryModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBorraryModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBorraryModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaBorraryModificar dialog = new VentanaBorraryModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAforo;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bBorrarTodo;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bFechayHoras;
    private javax.swing.JButton bLugar;
    private javax.swing.JButton bModificar;
    private javax.swing.JPanel jAforo;
    private javax.swing.JPanel jFechayHoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jLugar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcLugar;
    private javax.swing.JComboBox<String> jcNombreEvento;
    private javax.swing.JFormattedTextField jfAforo;
    private javax.swing.JFormattedTextField jfFecha;
    private javax.swing.JFormattedTextField jfHoraf;
    private javax.swing.JFormattedTextField jfHorai;
    private javax.swing.JPanel jpAforo;
    private javax.swing.JPanel jpFechayHoras;
    private javax.swing.JPanel jpLugar;
    // End of variables declaration//GEN-END:variables
}
