/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Producto;
import static javax.swing.JOptionPane.showMessageDialog;
import t7p3eje2.Controlador;

/**
 *
 * @author ketro
 */
public class Compra extends javax.swing.JDialog {

    private Producto producto;
    private int unidades;
    /**
     * Creates new form Compra
     */
    public Compra(java.awt.Frame parent, boolean modal, Producto producto, int unidades ) {
        super(parent, modal);
        initComponents();        
        
        this.producto = producto;
        this.unidades= unidades;
        
        mostrarDatos(producto);
        setLocationRelativeTo(null);
    }
    public void mostrarDatos(Producto producto){
        
        if (producto == null)
            return;
            
        Controlador.llenarProvedor(this.cbProvedor);
        float precioU = Controlador.mostrarprecioUnitarioCompra(producto.getNombre());
        this.tfPrecioUnitarioCompra.setText(String.valueOf(precioU));
                
    }
 
    public void limpiar(){
        this.tfPrecioUnitarioCompra.setText("");
        this.cbProvedor.setSelectedIndex(0);
        this.tfImporte.setText("");
        this.pCompra.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCompra = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfPrecioUnitarioCompra = new javax.swing.JTextField();
        tfImporte = new javax.swing.JTextField();
        cbProvedor = new javax.swing.JComboBox<>();
        tfComprar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Sobre la Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel4.setText("Precio :");

        jLabel5.setText("Provedor :");

        jLabel6.setText("Importe de la Compra :");

        tfPrecioUnitarioCompra.setEditable(false);
        tfPrecioUnitarioCompra.setBackground(new java.awt.Color(255, 255, 255));

        tfImporte.setEditable(false);

        cbProvedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione un Provedor" }));
        cbProvedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbProvedorFocusLost(evt);
            }
        });
        cbProvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProvedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCompraLayout = new javax.swing.GroupLayout(pCompra);
        pCompra.setLayout(pCompraLayout);
        pCompraLayout.setHorizontalGroup(
            pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCompraLayout.createSequentialGroup()
                .addGroup(pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCompraLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pCompraLayout.createSequentialGroup()
                        .addGroup(pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrecioUnitarioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        pCompraLayout.setVerticalGroup(
            pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfPrecioUnitarioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbProvedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tfComprar.setText("Comprar");
        tfComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfComprarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(tfComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(bCancelar)
                .addGap(109, 109, 109))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfComprar)
                    .addComponent(bCancelar))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProvedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbProvedorFocusLost
     Float importe = Controlador.mostrarImporteProductos(unidades);
     this.tfImporte.setText(String.valueOf(importe));
    }//GEN-LAST:event_cbProvedorFocusLost

    private void cbProvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProvedorActionPerformed

    }//GEN-LAST:event_cbProvedorActionPerformed

    private void tfComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfComprarActionPerformed
       
            int unidadesTotal = Controlador.anadirUnidadesAlStock(unidades);
            if (unidadesTotal > 0) {
                showMessageDialog(this, "Compra realizada!");
                limpiar();
                this.dispose();
                
            } else {
                showMessageDialog(this, "Compra NO realizada!");
            }
    }//GEN-LAST:event_tfComprarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
         Controlador.salir();
    }//GEN-LAST:event_bCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JComboBox<String> cbProvedor;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pCompra;
    private javax.swing.JButton tfComprar;
    private javax.swing.JTextField tfImporte;
    private javax.swing.JTextField tfPrecioUnitarioCompra;
    // End of variables declaration//GEN-END:variables
}
