/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Exception.CampoVacio;
import Exception.ProductoVacio;
import Modelo.Producto;
import static javax.swing.JOptionPane.showMessageDialog;
import t7p3eje2.Controlador;

/**
 *
 * @author ketro
 */
public class Venta extends javax.swing.JDialog {

    private Producto producto;
    private int unidades;
    /**
     * Creates new form Venta
     */
    public Venta(java.awt.Frame parent, boolean modal,Producto producto, int unidades) {
        super(parent, modal);
        
        this.producto=producto;
        this.unidades =unidades;        
        setLocationRelativeTo(null);
        initComponents();
        mostrarDatos(producto);
    }
    public void mostrarDatos(Producto producto){
        try {
            if (producto == null)
                throw new ProductoVacio();
                
            if (producto.getUnidades()==0) {
                throw new CampoVacio();
            } else {
                boolean respuesta = Controlador.comprobarCantidad(producto.getUnidades());
                if (respuesta == false) {
                    showMessageDialog(this, "No hay la cantidad suficiente para realizar la venta!");
                    limpiar();
                } else {
                    float precioVenta = Controlador.llamarPrecioVenta(producto.getUnidades());
                    if (precioVenta != 0) {
                        this.tfPrecioVenta.setText(String.valueOf(precioVenta));
                        this.tfImporteVenta.setText(String.valueOf(precioVenta));
                    } else {
                        showMessageDialog(this, "No si puede vender");
                    }
                }
            }
        } catch (ProductoVacio pv) {
            showMessageDialog(this, "El producto no puede estar vacío");
        }
        catch (CampoVacio cv) {
            showMessageDialog(this, "El campo no puede estar vacío");
        }
    }
    
   
    public void limpiar(){
        this.tfPrecioVenta.setText("");
        this.tfImporteVenta.setText("");
        this.pVenta.setVisible(true);
        this.tfCliente.setText("");
        this.cbxProntoP.setSelected(false);
        this.cbxVolumen.setSelected(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pVenta = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfPrecioVenta = new javax.swing.JTextField();
        tfCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cbxVolumen = new javax.swing.JCheckBox();
        cbxProntoP = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        tfImporteVenta = new javax.swing.JTextField();
        bVenta = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Sobre la Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel7.setText("Precio");

        jLabel8.setText("Cliente");

        tfPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecioVentaActionPerformed(evt);
            }
        });

        tfCliente.setText(" ");
        tfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfClienteActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descuentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        cbxVolumen.setText("Por Volumen");
        cbxVolumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVolumenActionPerformed(evt);
            }
        });

        cbxProntoP.setText("Por Pronto Pago");
        cbxProntoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProntoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cbxVolumen)
                .addGap(61, 61, 61)
                .addComponent(cbxProntoP)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxProntoP)
                    .addComponent(cbxVolumen))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel9.setText("Importe de la Venta");

        javax.swing.GroupLayout pVentaLayout = new javax.swing.GroupLayout(pVenta);
        pVenta.setLayout(pVentaLayout);
        pVentaLayout.setHorizontalGroup(
            pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pVentaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addComponent(tfImporteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pVentaLayout.createSequentialGroup()
                        .addGroup(pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pVentaLayout.createSequentialGroup()
                                .addGroup(pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pVentaLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfPrecioVenta))
                                    .addGroup(pVentaLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        pVentaLayout.setVerticalGroup(
            pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVentaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(pVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfImporteVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bVenta.setText("Vender");
        bVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVentaActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(bVenta)
                .addGap(111, 111, 111)
                .addComponent(bCancelar)
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVenta)
                    .addComponent(bCancelar))
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 65, Short.MAX_VALUE)
                    .addComponent(pVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 66, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecioVentaActionPerformed

    private void tfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfClienteActionPerformed
        Controlador.guardarCliente(this.tfCliente.getText());
    }//GEN-LAST:event_tfClienteActionPerformed

    private void cbxVolumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVolumenActionPerformed
      float importe = Controlador.descuento(this.cbxVolumen, this.tfPrecioVenta.getText(),producto.getUnidades(), this.cbxProntoP);
        if (importe != 0) {

            this.tfImporteVenta.setText(String.valueOf(importe));
        }
    }//GEN-LAST:event_cbxVolumenActionPerformed

    private void cbxProntoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProntoPActionPerformed
        float importeVenta = Controlador.descuento(this.cbxVolumen, this.tfPrecioVenta.getText(),producto.getUnidades(), this.cbxProntoP);
        if (importeVenta != 0) {
            this.tfImporteVenta.setText(String.valueOf(importeVenta));
        }
    }//GEN-LAST:event_cbxProntoPActionPerformed

    private void bVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVentaActionPerformed
        
            int unidadesTotal = Controlador.restarUnidadesAlStock(unidades);
            if (unidadesTotal > 0) {
                showMessageDialog(this, "Venta realizada!");
                limpiar();
                this.dispose();
                
            } else {
                showMessageDialog(this, "Venta NO realizada!");
            }
    }//GEN-LAST:event_bVentaActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
         Controlador.salir();
    }//GEN-LAST:event_bCancelarActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bVenta;
    private javax.swing.JCheckBox cbxProntoP;
    private javax.swing.JCheckBox cbxVolumen;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pVenta;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfImporteVenta;
    private javax.swing.JTextField tfPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
